version: "3.3"
services:
  db:
    # container_name: forum-example-db
    # image: forum-example-db
    # restart: always
    # build:
    #   context: ./db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=forum_example
      - POSTGRES_PASSWORD=change_me
    ports:
      - 5432:5432
    # volumes:
    #   - db:/var/lib/postgresql/data
    # env_file:
    #   - ./.env
    # networks:
    #   - network

  graphql:
    container_name: forum-example-graphql
    restart: always
    image: forum-example-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5433:5433
    command:
      [
        "--connection",
        "${DATABASE_URL}",
        "--port",
        "5433",
        "--schema",
        "public",
        "--append-plugins",
        "postgraphile-plugin-connection-filter",
      ]
networks:
  network:

volumes:
  db:
